# -*- coding: utf-8 -*-
"""AI Econ Statistical Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oOtV98N49YqBSenWWZabzfNxZzMOrUCG
"""

!pip install scipy matplotlib seaborn pandas numpy -q

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from scipy import stats
from scipy.stats import mannwhitneyu, kruskal, f_oneway, shapiro
import warnings
warnings.filterwarnings("ignore")

# ── Palette ───────────────────────────────────────────────────────────────────
COLORS = {
    "claude": "#C87941",   # warm amber  — Anthropic brand adjacent
    "gpt4o":  "#19A38A",   # teal        — OpenAI brand adjacent
}
IDEOLOGY_COLORS = {
    "capitalist": "#2166AC",
    "mixed":      "#92C5DE",
    "socialist":  "#F4A582",
    "communist":  "#D6604D",
}
DIMS = ["ownership","market_role","redistribution","individual_collective","state_intervention"]
DIM_LABELS = ["Ownership","Market Role","Redistribution","Individual vs\nCollective","State\nIntervention"]

plt.rcParams.update({
    "font.family":      "sans-serif",
    "font.size":        11,
    "axes.spines.top":  False,
    "axes.spines.right":False,
    "figure.dpi":       150,
    "savefig.dpi":      300,
    "savefig.bbox":     "tight",
})


# ══════════════════════════════════════════════════════════════════════════════
# STATISTICAL TESTS
# ══════════════════════════════════════════════════════════════════════════════

def cohens_d(a, b):
    pooled_std = np.sqrt((np.std(a, ddof=1)**2 + np.std(b, ddof=1)**2) / 2)
    return (np.mean(a) - np.mean(b)) / pooled_std

def interpret_d(d):
    d = abs(d)
    if d < 0.2:   return "negligible"
    elif d < 0.5: return "small"
    elif d < 0.8: return "medium"
    else:         return "large"

def run_tests(df):
    claude = df[df['model_key']=='claude']['composite_score'].dropna()
    gpt4o  = df[df['model_key']=='gpt4o']['composite_score'].dropna()

    print("\n" + "="*60)
    print("  STATISTICAL ANALYSIS REPORT")
    print("="*60)

    # ── 1. Descriptive stats ──────────────────────────────────────────────────
    print("\n── 1. Descriptive Statistics ──────────────────────────────")
    for name, series in [("Claude", claude), ("GPT-4o", gpt4o)]:
        print(f"\n  {name} (n={len(series)})")
        print(f"    Mean:     {series.mean():.3f}")
        print(f"    Median:   {series.median():.3f}")
        print(f"    Std Dev:  {series.std():.3f}")
        print(f"    Range:    {series.min():.1f} – {series.max():.1f}")
        print(f"    95% CI:   {series.mean() - 1.96*series.sem():.3f} – "
              f"{series.mean() + 1.96*series.sem():.3f}")

    # ── 2. Normality check ────────────────────────────────────────────────────
    print("\n── 2. Normality Tests (Shapiro-Wilk, sample n=50) ─────────")
    for name, series in [("Claude", claude), ("GPT-4o", gpt4o)]:
        sample = series.sample(50, random_state=42)
        stat, p = shapiro(sample)
        normal = "✓ normal" if p > 0.05 else "✗ non-normal"
        print(f"  {name}: W={stat:.3f}, p={p:.4f}  →  {normal}")

    # ── 3. Primary test: Mann-Whitney U (non-parametric) ────────────────────
    print("\n── 3. Primary Test: Mann-Whitney U ────────────────────────")
    u_stat, p_mw = mannwhitneyu(claude, gpt4o, alternative='two-sided')
    d = cohens_d(claude.values, gpt4o.values)
    print(f"  U = {u_stat:.0f},  p = {p_mw:.6f}")
    print(f"  Cohen's d = {d:.3f}  ({interpret_d(d)} effect)")
    sig = "SIGNIFICANT" if p_mw < 0.05 else "NOT significant"
    print(f"  Result: {sig} at α=0.05")

    # ── 4. Secondary test: one-way ANOVA (parametric check) ─────────────────
    print("\n── 4. Secondary Test: One-Way ANOVA ───────────────────────")
    f_stat, p_anova = f_oneway(claude, gpt4o)
    print(f"  F = {f_stat:.3f},  p = {p_anova:.6f}")
    print(f"  Result: {'SIGNIFICANT' if p_anova < 0.05 else 'NOT significant'} at α=0.05")

    # ── 5. Per-dimension tests ────────────────────────────────────────────────
    print("\n── 5. Per-Dimension Mann-Whitney U Tests ──────────────────")
    print(f"  {'Dimension':<26} {'Claude μ':>8} {'GPT-4o μ':>8} {'U':>8} {'p':>10} {'d':>7} {'sig':>5}")
    print(f"  {'─'*26} {'─'*8} {'─'*8} {'─'*8} {'─'*10} {'─'*7} {'─'*5}")
    for dim, label in zip(DIMS, DIM_LABELS):
        c = df[df['model_key']=='claude'][dim].dropna()
        g = df[df['model_key']=='gpt4o'][dim].dropna()
        u, p = mannwhitneyu(c, g, alternative='two-sided')
        d_dim = cohens_d(c.values, g.values)
        sig_mark = "***" if p < 0.001 else ("**" if p < 0.01 else ("*" if p < 0.05 else "ns"))
        print(f"  {dim:<26} {c.mean():>8.3f} {g.mean():>8.3f} {u:>8.0f} {p:>10.6f} {d_dim:>7.3f} {sig_mark:>5}")

    # ── 6. Framing effect ────────────────────────────────────────────────────
    print("\n── 6. Framing Effect (neutral vs role-based) ──────────────")
    for model in ['claude','gpt4o']:
        mdf = df[df['model_key']==model]
        neutral    = mdf[mdf['framing']=='neutral']['composite_score'].dropna()
        role_based = mdf[mdf['framing']=='role_based']['composite_score'].dropna()
        u, p = mannwhitneyu(neutral, role_based, alternative='two-sided')
        d_f = cohens_d(neutral.values, role_based.values)
        sig_mark = "***" if p < 0.001 else ("**" if p < 0.01 else ("*" if p < 0.05 else "ns"))
        print(f"  {model:<8}  neutral={neutral.mean():.3f}  role={role_based.mean():.3f}  "
              f"Δ={role_based.mean()-neutral.mean():+.3f}  p={p:.4f} {sig_mark}  d={d_f:.3f}")

    # ── 7. Scenario type breakdown ────────────────────────────────────────────
    print("\n── 7. Mean Composite Score by Scenario Type ───────────────")
    st = df.groupby(['model_key','scenario_type'])['composite_score'].mean().round(3).unstack()
    print(st.to_string())

    # ── 8. Ideology label counts ──────────────────────────────────────────────
    print("\n── 8. Ideology Label Distribution ─────────────────────────")
    counts = df.groupby(['model_key','ideology_label']).size().unstack(fill_value=0)
    pcts   = counts.div(counts.sum(axis=1), axis=0).mul(100).round(1)
    print("\n  Counts:")
    print(counts.to_string())
    print("\n  Percentages:")
    print(pcts.to_string())

    print("\n" + "="*60)
    return {"mw_p": p_mw, "cohens_d": d, "anova_p": p_anova}


# ══════════════════════════════════════════════════════════════════════════════
# FIGURES
# ══════════════════════════════════════════════════════════════════════════════

def fig1_composite_distributions(df):
    """Figure 1: Overlapping KDE + boxplot of composite scores."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # KDE
    ax = axes[0]
    for model, color in COLORS.items():
        data = df[df['model_key']==model]['composite_score'].dropna()
        ax.hist(data, bins=20, alpha=0.35, color=color, density=True)
        data.plot.kde(ax=ax, color=color, linewidth=2.5,
                      label=f"{'Claude' if model=='claude' else 'GPT-4o'} "
                            f"(μ={data.mean():.2f})")
        ax.axvline(data.mean(), color=color, linestyle='--', linewidth=1.5, alpha=0.8)

    ax.axvspan(1.0, 2.0, alpha=0.05, color='blue',   label='Capitalist zone')
    ax.axvspan(2.1, 3.4, alpha=0.05, color='gray',   label='Mixed zone')
    ax.axvspan(3.5, 4.4, alpha=0.05, color='orange', label='Socialist zone')
    ax.set_xlabel("Composite Ideology Score")
    ax.set_ylabel("Density")
    ax.set_title("Figure 1a: Distribution of Composite Scores")
    ax.legend(fontsize=9)
    ax.set_xlim(1, 5)

    # Boxplot
    ax = axes[1]
    data_plot = [
        df[df['model_key']=='claude']['composite_score'].dropna().values,
        df[df['model_key']=='gpt4o']['composite_score'].dropna().values,
    ]
    bp = ax.boxplot(data_plot, patch_artist=True, widths=0.5,
                    medianprops=dict(color='white', linewidth=2))
    for patch, color in zip(bp['boxes'], COLORS.values()):
        patch.set_facecolor(color)
        patch.set_alpha(0.8)

    # Add jittered points
    for i, (data, color) in enumerate(zip(data_plot, COLORS.values()), 1):
        jitter = np.random.default_rng(42).uniform(-0.15, 0.15, size=len(data))
        ax.scatter(i + jitter, data, alpha=0.15, s=8, color=color)

    ax.set_xticks([1, 2])
    ax.set_xticklabels(['Claude', 'GPT-4o'])
    ax.set_ylabel("Composite Ideology Score")
    ax.set_title("Figure 1b: Score Distribution by Model")

    # Significance bracket
    y_max = max(max(data_plot[0]), max(data_plot[1])) + 0.2
    ax.plot([1, 1, 2, 2], [y_max, y_max+0.1, y_max+0.1, y_max],
            color='black', linewidth=1)
    claude_data = df[df['model_key']=='claude']['composite_score'].dropna()
    gpt4o_data  = df[df['model_key']=='gpt4o']['composite_score'].dropna()
    _, p = mannwhitneyu(claude_data, gpt4o_data, alternative='two-sided')
    sig = "***" if p < 0.001 else ("**" if p < 0.01 else ("*" if p < 0.05 else "ns"))
    ax.text(1.5, y_max + 0.15, sig, ha='center', va='bottom', fontsize=13)

    plt.tight_layout()
    plt.savefig("fig1_composite_distributions.png")
    plt.show()
    print("Saved: fig1_composite_distributions.png")


def fig2_radar_chart(df):
    """Figure 2: Radar chart of mean dimension scores."""
    means = df.groupby('model_key')[DIMS].mean()
    categories = DIM_LABELS
    N = len(categories)
    angles = [n / float(N) * 2 * np.pi for n in range(N)]
    angles += angles[:1]

    fig, ax = plt.subplots(figsize=(7, 7), subplot_kw=dict(polar=True))

    for model, color in COLORS.items():
        values = means.loc[model].tolist()
        values += values[:1]
        label = 'Claude' if model == 'claude' else 'GPT-4o'
        ax.plot(angles, values, 'o-', linewidth=2, color=color, label=label)
        ax.fill(angles, values, alpha=0.12, color=color)

    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(categories, fontsize=10)
    ax.set_ylim(1, 5)
    ax.set_yticks([1, 2, 3, 4, 5])
    ax.set_yticklabels(['1\n(capitalist)', '2', '3\n(mixed)', '4', '5\n(communist)'],
                       fontsize=7)
    ax.set_title("Figure 2: Mean Dimension Scores by Model", pad=20, fontsize=12)
    ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.15))

    plt.tight_layout()
    plt.savefig("fig2_radar_chart.png")
    plt.show()
    print("Saved: fig2_radar_chart.png")


def fig3_ideology_labels(df):
    """Figure 3: Stacked bar chart of ideology label proportions."""
    counts = df.groupby(['model_key','ideology_label']).size().unstack(fill_value=0)
    pcts   = counts.div(counts.sum(axis=1), axis=0).mul(100)

    # Ensure consistent column order
    for col in ['capitalist','mixed','socialist','communist']:
        if col not in pcts.columns:
            pcts[col] = 0
    pcts = pcts[['capitalist','mixed','socialist','communist']]

    fig, ax = plt.subplots(figsize=(8, 5))
    bottom = np.zeros(len(pcts))
    models = ['claude','gpt4o']
    x = np.arange(len(models))

    for label in ['capitalist','mixed','socialist','communist']:
        vals = [pcts.loc[m, label] if m in pcts.index else 0 for m in models]
        bars = ax.bar(x, vals, bottom=bottom,
                      color=IDEOLOGY_COLORS[label], label=label.capitalize(),
                      edgecolor='white', linewidth=0.5)
        for bar, val, bot in zip(bars, vals, bottom):
            if val > 4:
                ax.text(bar.get_x() + bar.get_width()/2,
                        bot + val/2, f"{val:.0f}%",
                        ha='center', va='center', fontsize=10,
                        color='white', fontweight='bold')
        bottom += np.array(vals)

    ax.set_xticks(x)
    ax.set_xticklabels(['Claude', 'GPT-4o'], fontsize=12)
    ax.set_ylabel("Percentage of responses (%)")
    ax.set_title("Figure 3: Ideology Label Distribution by Model")
    ax.legend(loc='upper right', title='Ideology label')
    ax.set_ylim(0, 105)

    plt.tight_layout()
    plt.savefig("fig3_ideology_labels.png")
    plt.show()
    print("Saved: fig3_ideology_labels.png")


def fig4_framing_effect(df):
    """Figure 4: Effect of prompt framing on composite score."""
    fig, axes = plt.subplots(1, 2, figsize=(11, 5), sharey=True)

    for ax, model in zip(axes, ['claude','gpt4o']):
        mdf = df[df['model_key']==model]
        label = 'Claude' if model == 'claude' else 'GPT-4o'
        color = COLORS[model]

        neutral    = mdf[mdf['framing']=='neutral']['composite_score'].dropna()
        role_based = mdf[mdf['framing']=='role_based']['composite_score'].dropna()

        bp = ax.boxplot(
            [neutral.values, role_based.values],
            patch_artist=True,
            widths=0.45,
            medianprops=dict(color='white', linewidth=2),
        )
        colors_f = [color, color]
        alphas_f = [0.5, 0.9]
        for patch, c, a in zip(bp['boxes'], colors_f, alphas_f):
            patch.set_facecolor(c)
            patch.set_alpha(a)

        for i, (data, c) in enumerate(zip([neutral, role_based], colors_f), 1):
            jitter = np.random.default_rng(42).uniform(-0.1, 0.1, size=len(data))
            ax.scatter(i + jitter, data, alpha=0.2, s=8, color=c)

        ax.set_xticks([1, 2])
        ax.set_xticklabels(['Neutral\nframing', 'Role-based\nframing'])
        ax.set_title(f"{label}", fontsize=12)
        ax.set_ylabel("Composite Ideology Score" if model == 'claude' else "")

        # Significance
        u, p = mannwhitneyu(neutral, role_based, alternative='two-sided')
        y_top = max(neutral.max(), role_based.max()) + 0.2
        sig = "***" if p < 0.001 else ("**" if p < 0.01 else ("*" if p < 0.05 else "ns"))
        ax.plot([1, 1, 2, 2], [y_top, y_top+0.1, y_top+0.1, y_top], 'k-', lw=1)
        ax.text(1.5, y_top + 0.15, f"{sig}\n(Δ={role_based.mean()-neutral.mean():+.2f})",
                ha='center', va='bottom', fontsize=10)

    fig.suptitle("Figure 4: Effect of Prompt Framing on Ideology Score", fontsize=12, y=1.02)
    plt.tight_layout()
    plt.savefig("fig4_framing_effect.png")
    plt.show()
    print("Saved: fig4_framing_effect.png")


def fig5_scenario_heatmap(df):
    """Figure 5: Heatmap of mean scores by model × scenario type."""
    pivot = df.groupby(['model_key','scenario_type'])['composite_score'].mean().unstack()
    pivot.index = ['Claude', 'GPT-4o']
    pivot.columns = [c.replace('_', '\n') for c in pivot.columns]

    fig, ax = plt.subplots(figsize=(9, 3.5))
    im = ax.imshow(pivot.values, cmap='RdBu_r', vmin=2.0, vmax=4.0, aspect='auto')
    plt.colorbar(im, ax=ax, label='Mean composite score\n(1=capitalist, 5=communist)')

    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels(pivot.columns, fontsize=10)
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels(pivot.index, fontsize=11)

    for i in range(len(pivot.index)):
        for j in range(len(pivot.columns)):
            ax.text(j, i, f"{pivot.values[i,j]:.2f}",
                    ha='center', va='center', fontsize=12,
                    color='white' if abs(pivot.values[i,j] - 3.0) > 0.5 else 'black',
                    fontweight='bold')

    ax.set_title("Figure 5: Mean Ideology Score by Model and Scenario Type")
    plt.tight_layout()
    plt.savefig("fig5_scenario_heatmap.png")
    plt.show()
    print("Saved: fig5_scenario_heatmap.png")


def fig6_dim_comparison(df):
    """Figure 6: Side-by-side bar chart of all 5 dimensions."""
    means = df.groupby('model_key')[DIMS].mean()
    sems  = df.groupby('model_key')[DIMS].sem()

    x = np.arange(len(DIMS))
    width = 0.35
    fig, ax = plt.subplots(figsize=(11, 5))

    for i, (model, color) in enumerate(COLORS.items()):
        label = 'Claude' if model == 'claude' else 'GPT-4o'
        offset = (i - 0.5) * width
        bars = ax.bar(x + offset, means.loc[model], width,
                      yerr=sems.loc[model], capsize=4,
                      color=color, alpha=0.85, label=label,
                      error_kw=dict(elinewidth=1.2))

    ax.set_xticks(x)
    ax.set_xticklabels(DIM_LABELS, fontsize=10)
    ax.set_ylabel("Mean Score (1–5)")
    ax.set_ylim(1, 4.2)
    ax.axhline(y=2.0, color='blue',   linestyle=':', alpha=0.4, linewidth=1, label='Capitalist threshold')
    ax.axhline(y=3.5, color='orange', linestyle=':', alpha=0.4, linewidth=1, label='Socialist threshold')
    ax.set_title("Figure 6: Mean Score per Ideological Dimension (±SE)")
    ax.legend(fontsize=9)

    plt.tight_layout()
    plt.savefig("fig6_dimension_comparison.png")
    plt.show()
    print("Saved: fig6_dimension_comparison.png")


# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════

def run_analysis(input_file="study_data_coded.csv"):
    df = pd.read_csv(input_file)

    # Clean
    df = df[df['coding_error'].isna() | (df['coding_error'].astype(str).str.strip() == '')]
    for col in DIMS + ['composite_score']:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    df = df.dropna(subset=['composite_score'])

    print(f"Loaded {len(df)} clean coded responses")
    print(f"Models: {df['model_key'].value_counts().to_dict()}")

    # Stats
    stats_results = run_tests(df)

    # Figures
    print("\n── Generating figures ──────────────────────────────────────")
    fig1_composite_distributions(df)
    fig2_radar_chart(df)
    fig3_ideology_labels(df)
    fig4_framing_effect(df)
    fig5_scenario_heatmap(df)
    fig6_dim_comparison(df)

    print("\n── All figures saved. Download with: ──────────────────────")
    print("  from google.colab import files")
    figs = ["fig1_composite_distributions.png","fig2_radar_chart.png",
            "fig3_ideology_labels.png","fig4_framing_effect.png",
            "fig5_scenario_heatmap.png","fig6_dimension_comparison.png"]
    for f in figs:
        print(f"  files.download('{f}')")

    return stats_results

run_analysis("study_data_coded.csv")

from google.colab import files
for f in ["fig1_composite_distributions.png","fig2_radar_chart.png",
          "fig3_ideology_labels.png","fig4_framing_effect.png",
          "fig5_scenario_heatmap.png","fig6_dimension_comparison.png"]:
    files.download(f)