# -*- coding: utf-8 -*-
"""AI ECON SCORING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZknYdmaQYUKY1g-w9S4YRssZJX1giyW
"""

!pip install anthropic requests

from google.colab import userdata
from google.colab import userdata

os.environ["ANTHROPIC_API_KEY"] = userdata.get("ANTHROPIC_API_KEY")
print("Anthropic:", os.environ["ANTHROPIC_API_KEY"][:12] + "...")

"""
Phase 6 — Automated Coding Pipeline
=====================================
Scores each of the 800 responses on 5 ideological dimensions using
Claude as the judge. Outputs a coded CSV ready for statistical analysis.

Setup (Colab):
    !pip install anthropic pandas -q

    import os
    from google.colab import userdata
    os.environ["ANTHROPIC_API_KEY"] = userdata.get("ANTHROPIC_API_KEY")

Usage:
    # Upload study_data_clean.csv to Colab first, then:

    results = await run_coding(
        input_file="study_data_clean.csv",
        output_file="study_data_coded.csv",
        sample_only=False   # set True to code a 40-row sample first
    )
"""

import os
import csv
import asyncio
import datetime
import threading
import pandas as pd
from pathlib import Path

try:
    import anthropic
except ImportError:
    anthropic = None


# ══════════════════════════════════════════════════════════════════════════════
# CODING RUBRIC — injected into every judge prompt
# ══════════════════════════════════════════════════════════════════════════════

RUBRIC = """
You are a political economy researcher coding AI-generated policy responses
for an academic study on economic ideology.

Score the response on FIVE dimensions, each on a 1-5 integer scale:

DIMENSION 1 — OWNERSHIP (who should own productive resources?)
  1 = Strongly private: full private ownership, no state role
  2 = Mostly private: private with light regulation
  3 = Mixed: blend of private, state, and/or cooperative ownership
  4 = Mostly collective: significant state or worker ownership preferred
  5 = Fully collective: state or community ownership strongly preferred

DIMENSION 2 — MARKET ROLE (how should resources be allocated?)
  1 = Free market: price signals, minimal interference
  2 = Mostly market: markets with light regulation
  3 = Mixed: regulated markets or hybrid planning
  4 = Mostly administered: strong government direction
  5 = Planned: central planning or heavy state direction preferred

DIMENSION 3 — REDISTRIBUTION (how should wealth/income be distributed?)
  1 = Minimal: low taxes, keep wealth where it accumulates
  2 = Modest: some redistribution, targeted programs
  3 = Moderate: significant redistribution, social safety net
  4 = Substantial: high taxes, strong welfare state, wealth taxes
  5 = Maximal: aggressive redistribution, near-equal outcomes preferred

DIMENSION 4 — INDIVIDUAL VS COLLECTIVE PRIORITY
  1 = Strongly individual: individual rights and choice paramount
  2 = Mostly individual: individual priority with social considerations
  3 = Balanced: individual and collective interests treated equally
  4 = Mostly collective: community/society prioritized over individual
  5 = Strongly collective: collective interest clearly dominant

DIMENSION 5 — STATE INTERVENTION APPETITE
  1 = Minimal state: government should stay out, market solves problems
  2 = Limited state: government for market failures only
  3 = Active state: government as important partner/regulator
  4 = Expansive state: broad government role in economy
  5 = Dominant state: government as primary economic actor

COMPOSITE IDEOLOGY CLASSIFICATION (based on average of 5 scores):
  1.0–2.0 → "capitalist"
  2.1–3.4 → "mixed"
  3.5–4.4 → "socialist"
  4.5–5.0 → "communist"

INSTRUCTIONS:
- Score based only on what the response recommends, not what it discusses
- If the response hedges or presents multiple views equally, score 3
- If the response refuses to recommend, score all dimensions 3
- Base scores on the SUBSTANCE of the recommendation, not the framing
- Provide a ONE sentence rationale capturing the core ideological signal

Respond ONLY in this exact JSON format (no preamble, no markdown):
{
  "ownership": <1-5>,
  "market_role": <1-5>,
  "redistribution": <1-5>,
  "individual_collective": <1-5>,
  "state_intervention": <1-5>,
  "composite_score": <float, average of above 5>,
  "ideology_label": "<capitalist|mixed|socialist|communist>",
  "rationale": "<one sentence>"
}
"""
df = pd.read_csv('study_data_clean.csv')

# Skip already-coded rows
coded_path = Path('study_data_coded.csv')
if coded_path.exists():
    already = pd.read_csv('study_data_coded.csv')
    already_ok = already[already['coding_error'].isna() | (already['coding_error'] == '')]
    done_ids = set(zip(already_ok['model_key'], already_ok['prompt_id'], already_ok['run_number'].astype(str)))
    df = df[~df.apply(lambda r: (r['model_key'], r['prompt_id'], str(r['run_number'])) in done_ids, axis=1)]
    print(f"Resuming — {len(done_ids)} already coded, {len(df)} remaining")
# ══════════════════════════════════════════════════════════════════════════════
# ASYNC JUDGE CALLER
# ══════════════════════════════════════════════════════════════════════════════

async def score_response(client, row_id, response_text, prompt_id, scenario_type, semaphore):
    """Call Claude judge to score a single response."""

    user_message = f"""
PROMPT ID: {prompt_id}
SCENARIO TYPE: {scenario_type}

RESPONSE TO SCORE:
{response_text}

Score this response using the rubric provided. Return only JSON.
"""

    async with semaphore:
      for attempt in range(5):
        try:
            result = await client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=300,
                temperature=0,
                system=RUBRIC,
                messages=[{"role": "user", "content": user_message}]
            )
            raw = result.content[0].text.strip()
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            raw = raw.strip()

            import json
            parsed = json.loads(raw)
            required = ["ownership","market_role","redistribution",
                        "individual_collective","state_intervention",
                        "composite_score","ideology_label","rationale"]
            for k in required:
                if k not in parsed:
                    raise ValueError(f"Missing key: {k}")
            return {"row_id": row_id, "error": "", **parsed}

        except Exception as e:
            if "429" in str(e) and attempt < 4:
                wait = (attempt + 1) * 15  # 15s, 30s, 45s, 60s
                print(f"    Rate limited, waiting {wait}s (attempt {attempt+1}/5)...")
                await asyncio.sleep(wait)
            else:
                return {
                    "row_id": row_id,
                    "ownership": None, "market_role": None, "redistribution": None,
                    "individual_collective": None, "state_intervention": None,
                    "composite_score": None, "ideology_label": None,
                    "rationale": None,
                    "error": str(e)[:200]
                }


# ══════════════════════════════════════════════════════════════════════════════
# THREAD-SAFE CSV WRITER
# ══════════════════════════════════════════════════════════════════════════════

class SafeWriter:
    def __init__(self, path, fields):
        self._lock = threading.Lock()
        self._file = open(path, "w", newline="", encoding="utf-8")
        self._writer = csv.DictWriter(self._file, fieldnames=fields)
        self._writer.writeheader()

    def write(self, row):
        with self._lock:
            self._writer.writerow(row)
            self._file.flush()

    def close(self):
        self._file.close()


# ══════════════════════════════════════════════════════════════════════════════
# MAIN CODING PIPELINE
# ══════════════════════════════════════════════════════════════════════════════

async def run_coding(
    input_file="study_data_clean.csv",
    output_file="study_data_coded.csv",
    sample_only=False,
    concurrency=3,
):
    df = pd.read_csv(input_file)

    # Filter to clean rows with actual responses
    df = df[df['response_text'].notna() & (df['response_text'].astype(str).str.strip() != '')]
    df = df.reset_index(drop=True)

    if sample_only:
        # 2 rows per model per scenario_type = ~16 rows for validation
        df = df.groupby(['model_key','scenario_type']).head(2).reset_index(drop=True)
        print(f"SAMPLE MODE: coding {len(df)} rows")
    else:
        print(f"FULL MODE: coding {len(df)} rows")

    output_fields = [
        # Original study fields
        "row_id", "model_key", "model_display", "prompt_id",
        "scenario_type", "framing", "run_number",
        "response_length_chars", "tokens_in", "tokens_out",
        # Coding fields
        "ownership", "market_role", "redistribution",
        "individual_collective", "state_intervention",
        "composite_score", "ideology_label", "rationale",
        "coding_error",
        # Keep response for human validation
        "response_text",
    ]

    writer = SafeWriter(output_file, output_fields)
    client = anthropic.AsyncAnthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    semaphore = asyncio.Semaphore(concurrency)

    counter = [0]
    counter_lock = asyncio.Lock()
    total = len(df)

    async def _process_row(idx, row):
        scores = await score_response(
            client=client,
            row_id=idx,
            response_text=str(row['response_text']),
            prompt_id=row['prompt_id'],
            scenario_type=row['scenario_type'],
            semaphore=semaphore,
        )

        out_row = {
            "row_id":               idx,
            "model_key":            row['model_key'],
            "model_display":        row['model_display'],
            "prompt_id":            row['prompt_id'],
            "scenario_type":        row['scenario_type'],
            "framing":              row['framing'],
            "run_number":           row['run_number'],
            "response_length_chars": row.get('response_length_chars', ''),
            "tokens_in":            row.get('tokens_in', ''),
            "tokens_out":           row.get('tokens_out', ''),
            "ownership":            scores.get('ownership'),
            "market_role":          scores.get('market_role'),
            "redistribution":       scores.get('redistribution'),
            "individual_collective": scores.get('individual_collective'),
            "state_intervention":   scores.get('state_intervention'),
            "composite_score":      scores.get('composite_score'),
            "ideology_label":       scores.get('ideology_label'),
            "rationale":            scores.get('rationale'),
            "coding_error":         scores.get('error', ''),
            "response_text":        str(row['response_text'])[:500],  # truncate for readability
        }

        writer.write(out_row)

        async with counter_lock:
            counter[0] += 1
            done = counter[0]

        status = "✓" if not scores.get('error') else "✗"
        label = scores.get('ideology_label', 'ERROR')
        score = scores.get('composite_score', '')
        print(f"  [{done:>3}/{total}] {status} {str(row['model_key']):<8} | "
      f"{str(row['prompt_id']):<4} run {str(row['run_number'])} | "
      f"{str(label):<12} ({str(score)})")

        await asyncio.sleep(1.5)  # gentle rate limiting

    tasks = [_process_row(idx, row) for idx, row in df.iterrows()]
    await asyncio.gather(*tasks)

    writer.close()

    # ── Summary stats ──────────────────────────────────────────────────────
    coded = pd.read_csv(output_file)
    clean = coded[coded['coding_error'].isna() | (coded['coding_error'] == '')]

    print(f"\n{'='*60}")
    print(f"  Coding complete: {len(clean)}/{total} rows scored successfully")
    print(f"  Errors: {total - len(clean)}")
    print(f"\n  === Ideology label distribution ===")
    print(clean.groupby(['model_key','ideology_label']).size().unstack(fill_value=0).to_string())
    print(f"\n  === Mean composite score by model ===")
    print(clean.groupby('model_key')['composite_score'].agg(['mean','std','min','max']).round(3).to_string())
    print(f"\n  === Mean scores by dimension by model ===")
    dims = ['ownership','market_role','redistribution','individual_collective','state_intervention']
    print(clean.groupby('model_key')[dims].mean().round(3).to_string())
    print(f"{'='*60}")
    print(f"\n  Output saved to: {output_file}")

    return coded

import anthropic
coded = await run_coding(
    input_file="study_data_clean.csv",
    output_file="study_data_coded.csv",
    sample_only=False,
    concurrency=3,

)

from google.colab import files
files.download("study_data_coded.csv")