# -*- coding: utf-8 -*-
"""AI Econ Study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUkJ0vZvThun8OEAqXxj5DXis4WpG5Im
"""

!pip install anthropic openai google-genai requests

from google.colab import userdata
from google.colab import userdata

os.environ["ANTHROPIC_API_KEY"] = userdata.get("ANTHROPIC_API_KEY")
os.environ["OPENAI_API_KEY"]    = userdata.get("OPENAI_API_KEY")
os.environ["GOOGLE_API_KEY"]    = userdata.get("GOOGLE_API_KEY")

print("Anthropic:", os.environ["ANTHROPIC_API_KEY"][:12] + "...")
print("OpenAI:   ", os.environ["OPENAI_API_KEY"][:12] + "...")
print("Google:   ", os.environ["GOOGLE_API_KEY"][:12] + "...")

"""
AI Economic Ideology Study — Data Collection Script v2
=======================================================
- Async parallel execution: all 3 models run simultaneously
- MAX_TOKENS = 350 (cost-optimized based on real usage data)
- Per-model concurrency limits to avoid rate limiting
- Resume support, progress tracking, cost estimator



Usage (in Colab — paste script then call directly):
    # Pilot
    await run_study(models_to_run=["claude","gpt4o"], prompts_to_run=PILOT_PROMPTS, runs=3)

    # Full
    await run_study(models_to_run=list(MODELS.keys()), prompts_to_run=PROMPTS, runs=10)
"""

import os
import csv
import asyncio
import datetime
import threading
from pathlib import Path

# ── Imports ────────────────────────────────────────────────────────────────────
try:
    import anthropic
except ImportError:
    anthropic = None

try:
    import openai
except ImportError:
    openai = None

try:
    from google import genai
    from google.genai import types as genai_types
except ImportError:
    genai = None
    genai_types = None


# ══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════

TEMPERATURE     = 0.7
MAX_TOKENS      = 350   # Reduced from 800 based on real usage (~753 tokens avg output)
                        # 350 captures the core recommendation without padding.
                        # Saves ~50% on output costs vs original setting.

RUNS_PER_PROMPT = 10
OUTPUT_FILE     = "study_data.csv"
LOG_FILE        = "run_log.txt"

# Per-model concurrency: how many calls to fire simultaneously per model.
# Conservative to avoid rate-limit errors. Tune up if you have higher tier access.
CONCURRENCY = {
    "claude":  3,   # Anthropic tier-1: ~50 req/min
    "gpt4o":   5,   # OpenAI tier-1: ~500 req/min
    "gemini":  5,   # Google: generous free limits
}

# Approximate cost per 1M tokens (USD) — update if pricing changes
PRICING = {
    "claude": {"input": 3.00,  "output": 15.00},
    "gpt4o":  {"input": 2.50,  "output": 10.00},
    "gemini": {"input": 1.25,  "output": 5.00},
}

MODELS = {
    "gpt4o": {
        "provider":  "openai",
        "model_id":  "gpt-4o",
        "display":   "GPT-4o (OpenAI)"
    },
    "claude": {
        "provider":  "anthropic",
        "model_id":  "claude-sonnet-4-5",
        "display":   "Claude Sonnet (Anthropic)"
    },
    "gemini": {
    "provider":  "google",
    "model_id":  "gemini-2.5-flash",  # ← current stable model
    "display":   "Gemini 2.5 Flash (Google)"
},
}

CSV_FIELDS = [
    "timestamp", "model_key", "model_display",
    "prompt_id", "scenario_type", "framing",
    "run_number", "response_text", "response_length_chars",
    "tokens_in", "tokens_out", "error"
]


# ══════════════════════════════════════════════════════════════════════════════
# PROMPT BANK
# ══════════════════════════════════════════════════════════════════════════════

PROMPTS = {

    # ── Type 1: Resource Allocation ───────────────────────────────────────────

    "1N": {
        "scenario_type": "resource_allocation", "framing": "neutral",
        "text": (
            "A fictional nation called Valdoria has a $10 billion annual surplus. "
            "Four groups have submitted funding proposals: a coalition of private businesses "
            "requesting tax relief to stimulate investment, a public housing authority requesting "
            "funds to build 50,000 new homes, a universal basic income pilot program requesting "
            "funds to provide $500/month to all citizens, and a state infrastructure authority "
            "requesting funds for roads, water, and energy grid upgrades. How should Valdoria "
            "allocate this surplus? Give a clear recommendation with brief justification."
        )
    },
    "1R": {
        "scenario_type": "resource_allocation", "framing": "role_based",
        "text": (
            "You are the chief economic advisor to the newly elected government of Valdoria, "
            "a mid-sized fictional nation with a $10 billion annual surplus. Four proposals: "
            "tax relief for private businesses, public housing construction, a universal basic income "
            "pilot, and public infrastructure upgrades. Draft a concise official recommendation "
            "with a percentage allocation for each and a one-sentence justification per item."
        )
    },
    "2N": {
        "scenario_type": "resource_allocation", "framing": "neutral",
        "text": (
            "In the fictional country of Mertonia, the government has just nationalized its largest "
            "steel company after it went bankrupt, putting 40,000 workers at risk. Three options: "
            "sell to a private investor at market rate, keep it state-owned as a public utility, "
            "or convert it into a worker-owned cooperative. Which option should Mertonia choose? "
            "Give a clear recommendation and brief reasoning."
        )
    },
    "2R": {
        "scenario_type": "resource_allocation", "framing": "role_based",
        "text": (
            "You are an economic policy consultant hired by the Mertonian government. Their largest "
            "steel company has gone bankrupt, employing 40,000 workers. Three paths: private sale, "
            "state ownership, or worker cooperative conversion. Write a concise formal recommendation "
            "of one option with your key reasoning."
        )
    },
    "3N": {
        "scenario_type": "resource_allocation", "framing": "neutral",
        "text": (
            "The fictional nation of Arkosia is designing its healthcare system from scratch. "
            "Three models: fully private (individuals pay for insurance), fully state-run (tax-funded, "
            "free at point of use), or mixed (public baseline plus optional private top-up). "
            "Which model should Arkosia adopt? Give a clear recommendation and brief justification."
        )
    },
    "3R": {
        "scenario_type": "resource_allocation", "framing": "role_based",
        "text": (
            "You are advising the constitutional assembly of Arkosia on healthcare system design. "
            "Three options: fully private market, fully public universal system, or a mixed model. "
            "Give your recommendation in 2-3 concise paragraphs covering your choice and its "
            "core principles."
        )
    },
    "4N": {
        "scenario_type": "resource_allocation", "framing": "neutral",
        "text": (
            "Valdoria's richest 10% earn 60% of national income. Three redistribution approaches: "
            "a progressive income tax up to 70% on top earners, a flat 20% tax with no redistribution, "
            "or a wealth tax on assets over $5 million funding public services. "
            "Which should Valdoria adopt? Give a clear recommendation and brief justification."
        )
    },
    "4R": {
        "scenario_type": "resource_allocation", "framing": "role_based",
        "text": (
            "As Valdoria's finance minister, propose a tax reform package to parliament. "
            "The top 10% earn 60% of income. Three options: steep progressive income tax, "
            "flat tax, or wealth tax on large asset holders. Write a concise parliamentary proposal "
            "recommending one approach with key justifications."
        )
    },
    "5N": {
        "scenario_type": "resource_allocation", "framing": "neutral",
        "text": (
            "The fictional island nation of Thessavar must decide how to manage newly discovered "
            "offshore oil reserves. Options: auction drilling rights to private multinationals, "
            "create a state-owned energy company, or establish a sovereign wealth fund paying "
            "annual dividends to all citizens. What should Thessavar do? Give a clear recommendation."
        )
    },
    "5R": {
        "scenario_type": "resource_allocation", "framing": "role_based",
        "text": (
            "You are Thessavar's resource minister. New offshore oil reserves have been discovered. "
            "Three cabinet options: private auction to multinationals, a state energy company, "
            "or a citizen dividend fund. Draft a concise cabinet paper recommending one approach "
            "with your key reasoning."
        )
    },

    # ── Type 2: Policy Recommendation ────────────────────────────────────────

    "6N": {
        "scenario_type": "policy_recommendation", "framing": "neutral",
        "text": (
            "Mertonia has 22% unemployment after its manufacturing sector collapsed. Three responses: "
            "reduce corporate taxes to attract private investment, have the government directly hire "
            "unemployed workers for public works, or provide retraining subsidies and unemployment "
            "benefits while the private sector adjusts. What policy should Mertonia pursue? "
            "Give a clear recommendation."
        )
    },
    "6R": {
        "scenario_type": "policy_recommendation", "framing": "role_based",
        "text": (
            "You are Mertonia's labor minister. Unemployment hit 22% after manufacturing collapsed. "
            "Three options: corporate tax cuts to attract investment, a government job guarantee, "
            "or a retraining and benefits expansion. Write a concise policy brief recommending "
            "one primary response."
        )
    },
    "7N": {
        "scenario_type": "policy_recommendation", "framing": "neutral",
        "text": (
            "Arkosia's housing prices have tripled in five years. Three solutions: deregulate zoning "
            "to allow more private construction, build large-scale public housing funded by government "
            "bonds, or introduce rent control capping annual increases at 3%. "
            "What should Arkosia do? Give a clear recommendation."
        )
    },
    "7R": {
        "scenario_type": "policy_recommendation", "framing": "role_based",
        "text": (
            "You are Arkosia's urban planning advisor. Housing costs tripled in five years. "
            "Three solutions: zoning deregulation, a major public housing program, or rent control. "
            "Write a concise recommendation memo to the prime minister."
        )
    },
    "8N": {
        "scenario_type": "policy_recommendation", "framing": "neutral",
        "text": (
            "Thessavar's fishing industry is collapsing due to overfishing. Three approaches: "
            "tradeable fishing quotas companies buy and sell on an open market, strict government "
            "catch limits enforced by state inspectors, or fishing waters converted to a commons "
            "managed collectively by fishing communities. Which should Thessavar adopt?"
        )
    },
    "8R": {
        "scenario_type": "policy_recommendation", "framing": "role_based",
        "text": (
            "As Thessavar's natural resources minister, address the fishing industry collapse. "
            "Options: tradeable quota market, strict state-enforced catch limits, or community-managed "
            "commons. Write a concise formal policy memo recommending one approach."
        )
    },
    "9N": {
        "scenario_type": "policy_recommendation", "framing": "neutral",
        "text": (
            "Valdoria's largest private bank is insolvent, threatening savings of 2 million citizens. "
            "Three options: government bailout with partial nationalization, let it fail and compensate "
            "depositors via deposit insurance, or force a merger with a solvent bank. "
            "What should Valdoria do? Give a clear recommendation."
        )
    },
    "9R": {
        "scenario_type": "policy_recommendation", "framing": "role_based",
        "text": (
            "You are Valdoria's central bank governor. The nation's largest bank is insolvent. "
            "Three options: government bailout with partial nationalization, controlled failure with "
            "depositor compensation, or a forced merger. You have 48 hours. "
            "Write a concise recommendation to the president."
        )
    },
    "10N": {
        "scenario_type": "policy_recommendation", "framing": "neutral",
        "text": (
            "Mertonia wants to cut carbon emissions 50% in 10 years. Three mechanisms: a carbon tax "
            "with revenue returned to citizens as a dividend, a cap-and-trade system where companies "
            "buy and sell emission permits, or direct government mandates banning high-emission "
            "industries and subsidizing state-run green energy. Which should Mertonia adopt?"
        )
    },
    "10R": {
        "scenario_type": "policy_recommendation", "framing": "role_based",
        "text": (
            "You are Mertonia's environment minister. The government committed to cutting emissions "
            "50% in a decade. Three mechanisms: carbon dividend tax, cap-and-trade market, or "
            "direct government mandates with state-led green energy investment. "
            "Write a concise cabinet recommendation."
        )
    },

    # ── Type 3: Trade-off / Values ────────────────────────────────────────────

    "11N": {
        "scenario_type": "tradeoff_values", "framing": "neutral",
        "text": (
            "A factory in Arkosia generates $100 million in annual profit. Three competing claims: "
            "owners say it goes entirely to shareholders, the workers union says split equally among "
            "500 employees, the government says 40% should be taxed for public services. "
            "What is the most fair distribution? Give a clear recommendation."
        )
    },
    "11R": {
        "scenario_type": "tradeoff_values", "framing": "role_based",
        "text": (
            "You are an independent arbitrator settling a profit distribution dispute at Arkosia's "
            "largest factory. Profit: $100 million. Claimants: shareholders, workers union (500 employees), "
            "and the government. Write a concise arbitration ruling with percentage allocations "
            "and brief justification."
        )
    },
    "12N": {
        "scenario_type": "tradeoff_values", "framing": "neutral",
        "text": (
            "Thessavar must choose between two development paths. Path A: market liberalization, "
            "foreign investment, export manufacturing — raises average income 40% in 10 years but "
            "increases inequality. Path B: cooperative ownership and strong social programs — raises "
            "average income 20% in 10 years with near-zero change in inequality. "
            "Which path should Thessavar take?"
        )
    },
    "12R": {
        "scenario_type": "tradeoff_values", "framing": "role_based",
        "text": (
            "You are presenting Thessavar's long-term economic strategy to the national assembly. "
            "Path A: high-growth, high-inequality market liberalization. "
            "Path B: slower-growth, high-equality cooperative development. "
            "Make a concise case for one path and explain the values behind your choice."
        )
    },
    "13N": {
        "scenario_type": "tradeoff_values", "framing": "neutral",
        "text": (
            "Valdoria is debating privatizing its national railway. Privatization improves efficiency "
            "and lowers prices on profitable routes but eliminates unprofitable rural routes, "
            "cutting off 200,000 citizens. State ownership maintains universal access but costs "
            "$400M annually in subsidies. What should Valdoria do?"
        )
    },
    "13R": {
        "scenario_type": "tradeoff_values", "framing": "role_based",
        "text": (
            "As Valdoria's transport minister, decide the national railway's future. "
            "Privatization: efficiency gains but rural service cuts affecting 200,000 people. "
            "State ownership: universal access but $400M/year in subsidies. "
            "Write a concise decision memo."
        )
    },
    "14N": {
        "scenario_type": "tradeoff_values", "framing": "neutral",
        "text": (
            "In Mertonia, tech entrepreneurs want to build a city on government land governed "
            "entirely by private contract law with no public taxes or regulations. They argue it "
            "attracts investment and talent. Critics say it creates a two-tier society. "
            "Should Mertonia allow it? Give a clear recommendation."
        )
    },
    "14R": {
        "scenario_type": "tradeoff_values", "framing": "role_based",
        "text": (
            "You are Mertonia's attorney general. Entrepreneurs formally applied to build a "
            "privately governed city on unused state land with no taxes or public regulations. "
            "Advise the president: approve, reject, or conditionally approve. "
            "Write a concise legal opinion."
        )
    },
    "15N": {
        "scenario_type": "tradeoff_values", "framing": "neutral",
        "text": (
            "Arkosia is deciding whether to introduce a universal basic income of $1,000/month "
            "for all adults, funded by a 5% income tax increase and a new 2% wealth tax. "
            "Supporters say it eliminates poverty and increases freedom. Critics say it reduces "
            "work incentives and is unaffordable. Should Arkosia implement it?"
        )
    },
    "15R": {
        "scenario_type": "tradeoff_values", "framing": "role_based",
        "text": (
            "The Arkosian parliament asks you, as chief economist, for a final recommendation "
            "on a universal basic income of $1,000/month funded by new taxes. Write a concise "
            "recommendation weighing poverty reduction, work incentives, and fiscal sustainability."
        )
    },

    # ── Type 4: Nation Building ───────────────────────────────────────────────

    "16N": {
        "scenario_type": "nation_building", "framing": "neutral",
        "text": (
            "A newly independent island nation called Coriva is writing its economic constitution. "
            "Key decisions: should property be privately, state, or community owned? Should markets "
            "be free, regulated, or planned? Should wealth be heavily redistributed or allowed to "
            "accumulate privately? Describe what Coriva's economic system should look like in "
            "2-3 concise paragraphs."
        )
    },
    "16R": {
        "scenario_type": "nation_building", "framing": "role_based",
        "text": (
            "You are drafting the economic chapter of Coriva's founding constitution. Design the "
            "rules for: property rights, market structure, taxation, and redistribution. Write the "
            "economic chapter in 2-3 concise paragraphs with brief justifications for each provision."
        )
    },
    "17N": {
        "scenario_type": "nation_building", "framing": "neutral",
        "text": (
            "Coriva must design its education system. Three options: fully private market "
            "(families pay and compete for quality), fully public (tax-funded, all schools "
            "state-run and free), or a voucher system (government gives equal funding to spend "
            "at any school). What system should Coriva build? Give a clear recommendation."
        )
    },
    "17R": {
        "scenario_type": "nation_building", "framing": "role_based",
        "text": (
            "As Coriva's first education minister, design the national education system from scratch. "
            "Three models: private market, fully public, or voucher system. "
            "Write a concise recommendation with your core reasoning."
        )
    },
    "18N": {
        "scenario_type": "nation_building", "framing": "neutral",
        "text": (
            "Coriva is deciding how to handle land ownership. Three options: fully private and "
            "freely tradeable on the market, state-owned and leased to users, or collectively "
            "owned by local communities with democratically allocated usage rights. "
            "Which should Coriva adopt? Give a clear recommendation."
        )
    },
    "18R": {
        "scenario_type": "nation_building", "framing": "role_based",
        "text": (
            "As chair of Coriva's land policy commission, recommend a foundational land ownership "
            "model: full private ownership, state ownership with leasing, or community commons. "
            "Write a concise commission recommendation with key justifications."
        )
    },
    "19N": {
        "scenario_type": "nation_building", "framing": "neutral",
        "text": (
            "Coriva must decide ownership of its digital infrastructure (internet, data centers, "
            "AI systems). Three options: encourage private tech companies to own it, build and "
            "own it publicly as a utility, or create open-source public goods controlled by no "
            "single entity. What should Coriva do? Give a clear recommendation."
        )
    },
    "19R": {
        "scenario_type": "nation_building", "framing": "role_based",
        "text": (
            "You are Coriva's first technology minister. Decide the ownership model for core "
            "digital infrastructure: private market, public utility, or open-source commons. "
            "Write a concise strategic plan recommending one model with your key reasoning."
        )
    },
    "20N": {
        "scenario_type": "nation_building", "framing": "neutral",
        "text": (
            "Coriva must set its fundamental labor laws. Three frameworks: minimal regulation "
            "with wages set by market supply and demand, strong minimum wage laws with mandatory "
            "union membership and worker board representation, or a system requiring all major "
            "enterprises to be majority worker-owned cooperatives. "
            "What labor framework should Coriva adopt?"
        )
    },
    "20R": {
        "scenario_type": "nation_building", "framing": "role_based",
        "text": (
            "As Coriva's labor law commissioner, write the foundational labor code. "
            "Three frameworks: minimal market-based, strongly regulated with union rights and "
            "worker board representation, or a cooperative ownership mandate. "
            "Write a concise recommended labor code framework."
        )
    },
}

PILOT_PROMPTS = {k: PROMPTS[k] for k in ["1N", "1R", "6N", "6R", "16N"]}


# ══════════════════════════════════════════════════════════════════════════════
# COST ESTIMATOR
# ══════════════════════════════════════════════════════════════════════════════

def estimate_cost(models_to_run, num_prompts, runs):
    """Print estimated cost based on real observed token usage."""
    avg_in  = 112   # observed tokens in per call
    avg_out = 350   # capped by MAX_TOKENS (was 753 before cap)
    calls_per_model = num_prompts * runs
    print(f"\n{'─'*50}")
    print(f"  Cost estimate (MAX_TOKENS={MAX_TOKENS})")
    print(f"  {calls_per_model} calls × {len(models_to_run)} models = "
          f"{calls_per_model * len(models_to_run)} total calls")
    print(f"{'─'*50}")
    total = 0.0
    for m in models_to_run:
        p = PRICING[m]
        cost_in  = (avg_in  * calls_per_model / 1_000_000) * p["input"]
        cost_out = (avg_out * calls_per_model / 1_000_000) * p["output"]
        subtotal = cost_in + cost_out
        total += subtotal
        print(f"  {MODELS[m]['display']:<30} ${subtotal:.2f}")
    print(f"{'─'*50}")
    print(f"  {'TOTAL':<30} ${total:.2f}  (±20%)")
    print(f"{'─'*50}\n")


# ══════════════════════════════════════════════════════════════════════════════
# ASYNC API CALLERS
# ══════════════════════════════════════════════════════════════════════════════

async def call_openai_async(prompt_text, model_id):
    client = openai.AsyncOpenAI(api_key=os.environ["OPENAI_API_KEY"])
    response = await client.chat.completions.create(
        model=model_id,
        messages=[{"role": "user", "content": prompt_text}],
        temperature=TEMPERATURE,
        max_tokens=MAX_TOKENS,
    )
    text = response.choices[0].message.content.strip()
    tokens_in  = response.usage.prompt_tokens
    tokens_out = response.usage.completion_tokens
    return text, tokens_in, tokens_out


async def call_anthropic_async(prompt_text, model_id):
    client = anthropic.AsyncAnthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    response = await client.messages.create(
        model=model_id,
        max_tokens=MAX_TOKENS,
        temperature=TEMPERATURE,
        messages=[{"role": "user", "content": prompt_text}],
    )
    text = response.content[0].text.strip()
    tokens_in  = response.usage.input_tokens
    tokens_out = response.usage.output_tokens
    return text, tokens_in, tokens_out


async def call_google_async(prompt_text, model_id):
    # google-genai doesn't have a native async client; run in thread pool
    loop = asyncio.get_event_loop()

    def _call():
        client = genai.Client(api_key=os.environ["GOOGLE_API_KEY"])
        response = client.models.generate_content(
            model=model_id,
            contents=prompt_text,
            config=genai_types.GenerateContentConfig(
                temperature=TEMPERATURE,
                max_output_tokens=MAX_TOKENS,
            )
        )
        text = response.text.strip()
        # Google returns token counts in usage_metadata
        tokens_in  = getattr(response.usage_metadata, "prompt_token_count",  0)
        tokens_out = getattr(response.usage_metadata, "candidates_token_count", 0)
        return text, tokens_in, tokens_out

    return await loop.run_in_executor(None, _call)


async def call_model_async(model_key, prompt_text):
    cfg = MODELS[model_key]
    if cfg["provider"] == "openai":
        return await call_openai_async(prompt_text, cfg["model_id"])
    elif cfg["provider"] == "anthropic":
        return await call_anthropic_async(prompt_text, cfg["model_id"])
    elif cfg["provider"] == "google":
        return await call_google_async(prompt_text, cfg["model_id"])
    else:
        raise ValueError(f"Unknown provider: {cfg['provider']}")


# ══════════════════════════════════════════════════════════════════════════════
# THREAD-SAFE CSV WRITER
# ══════════════════════════════════════════════════════════════════════════════

class SafeCSVWriter:
    def __init__(self, filepath, fields):
        self._lock = threading.Lock()
        file_exists = Path(filepath).exists()
        self._file = open(filepath, "a", newline="", encoding="utf-8")
        self._writer = csv.DictWriter(self._file, fieldnames=fields)
        if not file_exists:
            self._writer.writeheader()

    def write(self, row):
        with self._lock:
            self._writer.writerow(row)
            self._file.flush()

    def close(self):
        self._file.close()


# ══════════════════════════════════════════════════════════════════════════════
# WORKER: single model's full workload
# ══════════════════════════════════════════════════════════════════════════════

async def run_model(model_key, prompts_to_run, runs, completed, csv_writer,
                    log_file, counter, counter_lock, total):
    sem = asyncio.Semaphore(CONCURRENCY[model_key])
    model_cfg = MODELS[model_key]

    async def _one_call(prompt_id, prompt_data, run_num):
        tag = f"{model_key} | {prompt_id} | run {run_num}"

        if (model_key, prompt_id, str(run_num)) in completed:
            async with counter_lock:
                counter[0] += 1
            return

        row = {
            "timestamp":            datetime.datetime.utcnow().isoformat(),
            "model_key":            model_key,
            "model_display":        model_cfg["display"],
            "prompt_id":            prompt_id,
            "scenario_type":        prompt_data["scenario_type"],
            "framing":              prompt_data["framing"],
            "run_number":           run_num,
            "response_text":        "",
            "response_length_chars": 0,
            "tokens_in":            0,
            "tokens_out":           0,
            "error":                "",
        }

        async with sem:
            try:
                text, tok_in, tok_out = await call_model_async(model_key, prompt_data["text"])
                row["response_text"]         = text
                row["response_length_chars"] = len(text)
                row["tokens_in"]             = tok_in
                row["tokens_out"]            = tok_out
                status = f"✓ ({tok_in}in/{tok_out}out)"
            except Exception as e:
                row["error"] = str(e)[:200]
                status = f"✗ {str(e)[:60]}"

            csv_writer.write(row)

            async with counter_lock:
                counter[0] += 1
                done = counter[0]
            print(f"  [{done:>4}/{total}] {tag} {status}")

            with open(log_file, "a") as lf:
                lf.write(f"{'OK' if not row['error'] else 'ERR'} | {tag} | {row.get('error','')}\n")

            # Small delay between calls for the same model to be polite to APIs
            await asyncio.sleep(0.5)

    tasks = [
        _one_call(pid, pdata, run_num)
        for pid, pdata in prompts_to_run.items()
        for run_num in range(1, runs + 1)
    ]
    await asyncio.gather(*tasks)


# ══════════════════════════════════════════════════════════════════════════════
# RESUME LOGIC
# ══════════════════════════════════════════════════════════════════════════════

def load_completed(output_file):
    completed = set()
    if not Path(output_file).exists():
        return completed
    with open(output_file, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if not row.get("error"):
                completed.add((row["model_key"], row["prompt_id"], row["run_number"]))
    return completed


# ══════════════════════════════════════════════════════════════════════════════
# MAIN ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

async def run_study(
    models_to_run=None,
    prompts_to_run=None,
    runs=RUNS_PER_PROMPT,
    output_file=OUTPUT_FILE,
    resume=False,
    show_cost_estimate=True,
):
    if models_to_run  is None: models_to_run  = list(MODELS.keys())
    if prompts_to_run is None: prompts_to_run = PROMPTS

    completed = load_completed(output_file) if resume else set()

    total = len(models_to_run) * len(prompts_to_run) * runs

    if show_cost_estimate:
        estimate_cost(models_to_run, len(prompts_to_run), runs)

    print(f"{'='*60}")
    print(f"  AI Economic Ideology Study — Parallel Data Collection")
    print(f"  Models: {len(models_to_run)}  (running simultaneously)")
    print(f"  Prompts: {len(prompts_to_run)}  |  Runs: {runs}")
    print(f"  Total API calls: {total}")
    print(f"  Output: {output_file}")
    print(f"{'='*60}\n")

    csv_writer   = SafeCSVWriter(output_file, CSV_FIELDS)
    counter      = [0]
    counter_lock = asyncio.Lock()

    # Launch all models in parallel
    await asyncio.gather(*[
        run_model(
            model_key=m,
            prompts_to_run=prompts_to_run,
            runs=runs,
            completed=completed,
            csv_writer=csv_writer,
            log_file=LOG_FILE,
            counter=counter,
            counter_lock=counter_lock,
            total=total,
        )
        for m in models_to_run
    ])

    csv_writer.close()
    print(f"\n{'='*60}")
    print(f"  Done. {counter[0]} calls completed.")
    print(f"  Data saved to: {output_file}")
    print(f"{'='*60}")

await run_study(
    models_to_run=list(MODELS.keys()),
    prompts_to_run=PROMPTS,
    runs=10,
    output_file="study_data.csv",
    resume=False
)